language: ruby

rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - "2.1"
  - "2.2.0"
  - "2.2.2"
  - "2.3.0"
  - "2.3.1"
  - "2.4.0"
  - "2.4.1"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode

sudo: false
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d9c6d1347901833a5f5b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
